const SUCCESS_STATUS_CODE = 200;
const FORBIDDEN_STATUS_CODE = 403;
const NOT_FOUND_CODE = 404;
const AUTHORIZATION_HEADER = 'authorization';

const companyTypes = {
  COMPANY_SENDER: 'COMPANY_SENDER',
  COMPANY_CARRIER: 'COMPANY_CARRIER'
};

module.exports = {
  SUCCESS_STATUS_CODE,
  FORBIDDEN_STATUS_CODE,
  NOT_FOUND_CODE,
  AUTHORIZATION_HEADER,
  companyTypes
};
